### ISSUE TITLE
No more ObservedItem?

### ISSUE THREAD

**Issue by fortylines** [pinax/pinax-notifications#10]
Hi,

I am not sure if it is the correct place to ask for this but here it is. I upgraded django-notification through pip from version 0.2 to version 1.0 and models.ObservedItem disappeared. I wanted to understand why but this new "official" repository was initialized recently without any previous history.
Is there a new Django-way that makes the models.ObservedItem unnecessary? Why did it get dropped from the repo?

Thanks,
Seb.

**Comment by grahamu** [comment]
It looks like `ObservedItem` was deprecated long ago, sorry.
