### ISSUE TITLE
No way to view notices on signing in

### ISSUE THREAD

**Issue by rhunwicks** [pinax/pinax-notifications#19]
The `README.rst` says:

```
The project aims to provide a Django app for this sort of functionality. This includes:

* notification messages on signing in
```

I think this functionality used to be provided by the `notices` view, which was removed by a2fd330c11a64dfdf047f2243ff467d143e2921c.

I can't find any issue or message explaining why this functionality (which seems like a really good idea) was removed.

Therefore, I guess this is either:
- an issue with that _view notices_ functionality, if it is still part of the scope of the app
- or an issue with the documentation, if it is no longer part of the current or future functionality

**Comment by MiltonLn** [comment]
I have the same needs, is there an answer for this?

**Comment by grahamu** [comment]
The documentation has been corrected, removing the "notification messages on signing in" feature.
