### ISSUE TITLE
Python 3.2 not supported

### ISSUE THREAD

**Issue by MickaelBergem** [pinax/pinax-notifications#41]
Hello,

I noticed (in production, too bad ^^) that `django-notification` was not compatible with Python 3 before Python3.3, because `get_ident` from the `threading` module is new in Python3.3 (https://docs.python.org/3/library/threading.html#threading.get_ident).

I don't know where to put this kind of requirements in the documentation / README, where should we put it ?

**Comment by grahamu** [comment]
Django/Python requirements are addressed in the recent update supporting Django 2.0
