### ISSUE TITLE
Migration fails with Django-1.7.x

### ISSUE THREAD

**Issue by jantoniomartin** [pinax/pinax-notifications#48]
When running `python manage.py migrate` with Django-1.7.8, an exception is thrown and the migration fails. The relevant part of the traceback is this:

    ValueError: Lookup failed for model referenced by field notifications.NoticeSetting.scoping_content_type: contenttypes.ContentType

**Comment by jantoniomartin** [comment]
Adding `('contenttypes', '__first__')` as a dependency to the migration seems to solve this problem, but then a different exception is thrown:

    ValueError: Lookup failed for model referenced by field notifications.NoticeSetting.user: auth.User

If I add ` ('auth', '__first__')` as a dependency, then the error is:

    django.db.utils.OperationalError: (1005, 'Can\'t create table `app_dev`.`#sql-903_12fd` (errno: 150 "Foreign key constraint is incorrectly formed")')

**Comment by jantoniomartin** [comment]
I can confirm that this problem is the same with Django-1.7.9.dev20150528142627.

**Comment by jantoniomartin** [comment]
I have found a workaround for this problem:
In the migration `0001_initial.py`, add only `('auth', '__first__') as a dependency.

I could send a pull request, but I don't know if manually editing the migration is appropriate.

**Comment by nsh87** [comment]
Would be great to get this into pypi, I've had to downgrade to 2.0.1 to continue to be able to migrate.

**Comment by marcinn** [comment]
How about pypi bugfix release?

**Comment by paltman** [comment]
@jantoniomartin editing migrations are fine. in fact, you should just consider `makemigrations` suggestions. You as the developer ultimately have more context for how things will be used than the code generating migrations.  In any event, we have hit and documented this problem (or at least one similar to it) on the Eldarion blog - http://eldarion.com/blog/2015/05/04/migrations-and-missing-constraints-in-django-17/.  I'd love to see your PR as it's unclear to me exactly what you are trying to do to solve it based on your comments.

**Comment by paltman** [comment]
Pushed 3.0.0 to PyPI. There are some minor changes from 2.1.0 to 3.0.0 but it drops support for Python 2.6 and Django 1.6 so I think it warranted a major release.

**Comment by peterfarrell** [comment]
We're seeing issues still with 3.0.x on Django 1.7.x.  I'm having my teammate comment on the solution shortly.

**Comment by mc-funk** [comment]
This is still a problem after [48] (https://github.com/pinax/pinax-notifications/issues/48).  Adding   ('contenttypes', '0001_initial') as a dependency after line 13 in 0001_initial.py is necessary to proceed without the error. That dependency is also generated by makemigrate in 1.7.9 if the original 0001_initial.py is deleted. Until a change is made to address this, this ticket should be re-opened. 

cc: @peterfarrell

**Comment by peterfarrell** [comment]
+1 on least breakage prone solution to use `__latest__` instead of version checking.

**Comment by psychok7** [comment]
upgraded to version 3.0.0 and i am getting with Django 1.7.9 :

```
Running migrations:
  Applying notifications.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/home/vagrant/.virtualenvs/xxx/local/lib/python2.7/site-packages/django/db/migrations/state.py", line 94, in render
    raise ValueError(msg.format(field=operations[0][1], model=lookup_model))
ValueError: Lookup failed for model referenced by field notifications.NoticeSetting.scoping_content_type: contenttypes.ContentType
```
