### ISSUE TITLE
Migration fails with Django-1.8.2 and MariaDB

### ISSUE THREAD

**Issue by jantoniomartin** [pinax/pinax-notifications#49]
After trying to solve issue #48 without success, I decided to try with Django-1.8.2 and a new, empty database. When running `python manage.py migrate`, this is the exception I get:

    django.db.utils.OperationalError: (1005, 'Can\'t create table `app_dev`.`#sql-903_12fd` (errno: 150 "Foreign key constraint is incorrectly formed")')

Then I have tried a new sqlite3 database and the migration runs correctly.

**Comment by jantoniomartin** [comment]
I have made more tests and this is not a bug in pinax-notifications. My apologies.

**Comment by dcotet** [comment]
@jantoniomartin  I am currently have this exact same trouble. How do you resolved that issue ?

**Comment by alaa-aqeel** [comment]
[solved this way](https://stackoverflow.com/questions/40429617/django-db-utils-operationalerror-1005-cant-create-table-xyz-sql-600-237/40430828#40430828)
