### ISSUE TITLE
Additional backends

### ISSUE THREAD

**Issue by jantoniomartin** [pinax/pinax-notifications#51]
I need to recover the possibility to show notices on the website, so I want to make a new backend to get this functionality.
Which is the best approach to do this?

My first try has been to make a separated app with the new backend and a Notice model. However, this creates a new migration in `pinax-notifications` because of `pinax.notifications.utils.load_media_defaults`, which alters the field `NoticeSetting.medium`.

A different approach would be adding this new backend directly to `pinax-notifications`, but I don't know if this is something that could be eventually accepted.

And a last possibility would be adding it to my own fork.

Maybe @paltman could shed some light on this subject before I take one of the options.

**Comment by jantoniomartin** [comment]
I have finally decided to use the first approach, since I think it is the best option.

My workaround to prevent the creation of a migration in `pinax-notifications` has been to remove this app from `settings.INSTALLED_APPS` before running `makemigrations`. This way, the migration is not created but my backend doesn't appear in the choices for `NoticeSetting.medium` which, on the other hand, I'm not sure what it's used for.

When finished, I will share my application as an example of an additional backend for `pinax-notifications`.

**Comment by jantoniomartin** [comment]
Just in case some of you are interested, this is my example of how to add a new backend to `pinax-notifications`:
https://github.com/jantoniomartin/condottieri_notification

**Comment by paltman** [comment]
This is great @jantoniomartin! I remain torn on what backends should be included in the package and what should be added via external packages.

**Comment by psychok7** [comment]
I have been working on a few additional backends myself,please have a look here: https://github.com/psychok7/pinax-notifications-backends
