### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by stringsonfire** [pinax/pinax-notifications#55]
I can't see any documentation for this app.

**Comment by psychok7** [comment]
do you mean this https://pinax-notifications.readthedocs.org/en/latest/usage/ ?

**Comment by stringsonfire** [comment]
Thanks. The link in `README.rst` on https://github.com/pinax/pinax-notifications points to http://pinaxproject.com/pinax/, and from there I couldn't find anything useful. Could https://pinax-notifications.readthedocs.org/en/latest/ be added to the readme?

**Comment by psychok7** [comment]
@stringsonfire if you make a Pull Request i am pretty sure the guys will accept that

**Comment by brosner** [comment]
Many of us from the Pinax team will be sprinting on Pinax during DjangoCon. A pull request is most welcome and we will be getting things tidied up too!

**Comment by ossanna16** [comment]
I added the link to the docs a while ago, therefore closing this issue.
