### ISSUE TITLE
Extending missing "account/base.html"

### ISSUE THREAD

**Issue by jelko** [pinax/pinax-notifications#58]
Notifications settings page is extending base template `account/base.html` which does not come with Django. (It comes with pinax themes though.)
This should either be documented or extend a template that exists by default.

```
TemplateDoesNotExist at /notifications/settings/
account/base.html
```

**Comment by bnisevic** [comment]
Yup it would be useful to put it here:
https://pinax-notifications.readthedocs.io/en/latest/usage/#notification-templates

**Comment by grahamu** [comment]
@jelko pinax-notifications now uses pinax-templates (if installed) for default templates. These include `account/base.html` as seen here: https://github.com/pinax/pinax-templates/blob/master/pinax/templates/templates/account/base.html. Thanks for pointing out this issue!
