### ISSUE TITLE
GenericRelation for user in NoticeSetting

### ISSUE THREAD

**Issue by svmalvaez** [pinax/pinax-notifications#64]
Is there a way to create notifications for multiple type of users (using different models for each one)?

in NoticeSetting the user FK is AUTH_USER_MODEL so it just point to one type of user :/

**Comment by ossanna16** [comment]
@jtauber @paltman Can one of you please help?

**Comment by grahamu** [comment]
@svmalvaez sorry, pinax-notifications only works with a single User model, as defined by `settings.AUTH_USER_MODEL`.
