### ISSUE TITLE
migrations with OneToOneField to NoticeType fail

### ISSUE THREAD

**Issue by grudelsud** [pinax/pinax-notifications#65]
not sure it's a pinax.notifications issue, I have this problem:

one of my models has a field defined as

```
notice_type = models.OneToOneField(
    'notifications.NoticeType',
    on_delete=models.CASCADE)
```

when running `./manage.py makemigrations` the following dependency is created

```
# note the date following 0002_auto_ depending on when makemigrations was invoked
('notifications', '0002_auto_20160513_1548'),
```

all works fine if I run `./manage.py migrate` on the same machine where I created migrations, but on another machine I get the following:

```
django.db.migrations.exceptions.NodeNotFoundError: Migration core.0001_initial dependencies reference nonexistent parent node (u'notifications', u'0002_auto_20160513_1548')
```

any advise and/or workaround would be great

thanks

**Comment by ossanna16** [comment]
@paltman @brosner @jtauber Could one of you please help with this?

**Comment by grudelsud** [comment]
bump. does anyone have recommendations on how to circumvent this problem, please?

the only solution we've found so far is to update our auto-generated migration file by replacing the dependency with

        ('notifications', '0001_initial'),

and that seems to work, although not sure it covers further updates done to the notifications package. please let me know

**Comment by ossanna16** [comment]
@paltman @jtauber @brosner Can one of you please help?

**Comment by grahamu** [comment]
@grudelsud The correct pinax-notifications migration reference is now ('pinax_notifications', '0002_auto_20171003_2006').
