### ISSUE TITLE
the lock in send_all() [engine.py Line 41] doesn't work

### ISSUE THREAD

**Issue by chowyi** [pinax/pinax-notifications#69]
not sure it's a pinax.notifications issue:

In the function **send_all()** of file **engine.py** ,
the **lock** seems have no effect.
when **lock** is None, the code below can still run.

```
def send_all(*args):
    lock = acquire_lock(*args)
    batches, sent, sent_actual = 0, 0, 0
    start_time = time.time()
    ……
```

Did I use it in the wrong way ? Thank you.

**Comment by grahamu** [comment]
Good catch @chowyi, I noticed the same issue when running simultaneous tests. I believe the solution is wrapping subsequent send_all() code in an `if lock:` conditional.
