### ISSUE TITLE
Please update django-notification Pypi page to make it clear it's deprecated

### ISSUE THREAD

**Issue by Flimm** [pinax/pinax-notifications#71]
`django-notification` is the old version of `pinax-notifications`. If you go to the [Pypi page of `django-notification`](https://pypi.python.org/pypi/django-notification), there is no indication that it has been replaced with `pinax-notifications`. Could `django-notification` be updated and published so that a link is clearly there on the Pypi page?

**Comment by paltman** [comment]
Good call. Thanks.

**Comment by grahamu** [comment]
@paltman bump, this is a very good point, and requires someone with ability to muck with django-notification on PyPi.

**Comment by grahamu** [comment]
@paltman bump

**Comment by KatherineMichel** [comment]
I'm happy to update this and close issue if someone wants to give me access. @paltman @jtauber

**Comment by KatherineMichel** [comment]
Closing issue. At this point, people can see for themselves that it's an old package.
