### ISSUE TITLE
App 'pinax.notifications' could not be found. Is it in INSTALLED_APPS?

### ISSUE THREAD

**Issue by SundialServices** [pinax/pinax-notifications#83]
_"Why, yes it is!"_  So, exactly why can't `manage.py` find it?

```
INSTALLED_APPS = [
[...]
    'pinax.notifications',
```

**Comment by grahamu** [comment]
@SundialServices you'll have to provide a bit more information. This sounds like a project configuration issue. Perhaps you can show your settings.py INSTALLED_APPS?

**Comment by SundialServices** [comment]
I found that by changing the INSTALLED_APPS entry to `pinax`, instead of `pinax.notifications` as the documentation states, solved the problem.  `makemigrations` then found all of the migrations, for the notifications component and otherwise.

I'm using Django 1.19 for other unrelated reasons, but I don't think that matters.

I'm closing the ticket because a solution or work-around has been found, but could this be a (wide-spread) documentation error?
