### ISSUE TITLE
account.models.Account doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by ondrejchmelar** [pinax/pinax-notifications#90]
I've encountered

> RuntimeError: Model class account.models.Account doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

after upgrading Django to 1.11.

This can be resolved by adding 'account' to INSTALLED_APPS but I don't think that should be needed.

Can you suggest what might be wrong? Thank you

**Comment by KatherineMichel** [comment]
@ondrejchmelar Are you installing this into a starter project? Which one? Perhaps the error is unrelated to pinax-notifications.

**Comment by ondrejchmelar** [comment]
Turned out to be a problem with django-user-accounts. Sorry to bother you.

**Comment by KatherineMichel** [comment]
@ondrejchmelar No problem. Glad you were able to figure it out.

**Comment by berinhard** [comment]
Any clue on how you solved this issue @ondrejchmelar ? I'm facing the same problem too (cc @renatooliveira)

**Comment by ondrejchmelar** [comment]
No idea, sorry.
