### ISSUE TITLE
 Apps aren't loaded yet.

### ISSUE THREAD

**Issue by sergioaguilera95** [pinax/pinax-notifications#92]
I'm using django 1.11.18 and every time I try to makemigrations this error comes up 
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by KatherineMichel** [comment]
@sergioaguilera95 I'm not sure how to help. I cloned the repo, created a virtualenv and ran ```python makemigrations.py``` and had no problem. I think that error is referring to this Django file and line: https://github.com/django/django/blob/24b82cd201e21060fbc02117dc16d1702877a1f3/django/apps/registry.py#L127
The apps listed in the makemigrations.py default settings normally just work. Have you added code somewhere that has created a conflict?

**Comment by KatherineMichel** [comment]
Closing due to no response. Assuming resolved.
