### ISSUE TITLE
How does pinax-notification choose the appropriate backend?

### ISSUE THREAD

**Issue by lggwettmann** [pinax/pinax-notifications#95]
Once I have multiple backends implemented, how does pinax-notifications choose which one to use for a specific notification? Or how can I send a notification with a specific backend?

**Comment by KatherineMichel** [comment]
I haven't completely grokked how it works, but looks like there is a function ```can_send` that determines whether the default backend "is allowed to send a notification to the given user and notice_type." Perhaps ```medium_id``` or ```scoping``` determine which backend should be used?  https://github.com/pinax/pinax-notifications/blob/master/pinax/notifications/backends/base.py#L17

**Comment by lggwettmann** [comment]
Ah thanks. Then I guess one has to implement a UI for that oneself. That's fine. Thanks for letting me know @KatherineMichel :)
