### ISSUE TITLE
Do pinax work on lastes version of django?

### ISSUE THREAD

**Issue by dldamian** [pinax/pinax-notifications#98]
Current version es 3.0.6, pinax would work fine if i install it on my project with the lastest version of django? regards

**Comment by KatherineMichel** [comment]
The supported versions matrix shows the versions of Python/Django supported in the most recently published package. We do have a branch that will be published as part of a new release... in that branch, the Python/Django versions have been dropped/added based on which ones are currently officially supported. https://github.com/pinax/pinax-notifications#supported-django-and-python-versions
