### ISSUE TITLE
When will the release happen for Django 3.0

### ISSUE THREAD

**Issue by SanketDG** [pinax/pinax-notifications#99]
I see that this package already has support for Django 3.0, can someone confirm and make a release?

**Comment by barclaey** [comment]
Good point, there has not been a release since 2018. Is this package fading away? Can someone clarify the state of the package?

**Comment by KatherineMichel** [comment]
Hello, @SanketDG, @barclaey... I've published a new release today. Let me know if you need anything else! https://pypi.org/project/pinax-notifications/6.0.0/
